name: Linting Workflow

on:
  push:
    branches:
      - "**"

jobs:
  python_lint:
    name: Python linting and formatting checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting libraries
        run: |
          set -e
          python3 -m pip install "ruff~=0.6"

      - name: Check Python files using Ruff
        run: |
          set -e
          ruff check --output-format github --config pyproject.toml .
          ruff format --diff --config pyproject.toml .

  prettier_lint:
    name: Prettier Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16" # Specify the Node.js version you want to use

      - name: Check files using Prettier
        run: |
          npm install -g prettier@3.3.2
          prettier --check .
